In [1]:
import pandas as pd


df = pd.read_excel('log_B.xlsx')

# df['del_G_eV'] = df['del G (eV) Paul'].fillna(df['del G (eV) Azida']).fillna(df['del G (eV) NBS'])
df['del_G_eV'] = df['del G (eV) Paul'].fillna(df['del G (eV) Azida']).fillna(df['del G (eV) Other'])

df = df[~df['ligand'].str.contains('NH4', na=False)]
df = df[~df['ligand'].str.contains('OH', na=False)]
df = df[~df['ligand'].str.contains('Cl', na=False)]
# df = df[~df['ligand'].str.contains('CN', na=False)]

new_df = df[['ligand', 'metal_ion', 'n_metal', 'n_complex', 'signed_metal_ion', 'del_G_eV','reference']]

new_df=new_df.dropna(how='any')
new_df

,ligand,metal_ion,n_metal,n_complex,signed_metal_ion,del_G_eV,reference
0,NH3,Ag+,1,1,Ag[1+],0.321990,Bjerrum1957StabilitySubstances
1,NH3,Ag+,1,2,Ag[1+],-0.190677,Bjerrum1957StabilitySubstances
2,NH3,Au+,1,2,Au[1+],-0.325391,Bjerrum1957StabilitySubstances
3,NH3,Au3+,1,4,Au[3+],1.681275,Bjerrum1957StabilitySubstances
4,NH3,Ca2+,1,1,Ca[2+],-6.001205,Bjerrum1957StabilitySubstances
...,...,...,...,...,...,...,...
141,CN[1-],Zn2+,1,4,Zn[2+],4.633763,Smith1989CriticalConstants
142,CN[1-],Pt2+,1,4,Pt[2+],5.646346,Bard2017StandardSolution
144,NO2[1-],Cu2+,1,1,Cu[2+],0.274026,Smith1989CriticalConstants
145,NO2[1-],Cu2+,1,2,Cu[2+],-0.072720,Smith1989CriticalConstants
146,NO2[1-],Cu2+,1,3,Cu[2+],-0.360299,Smith1989CriticalConstants

In [2]:
new_df

def extract_ion_number(expression):
    if "[" in expression and "]" in expression:
        ion = expression[expression.find("[") + 1 : expression.find("]")]
        return int(ion.replace("+", "").replace("-", "")) * (-1 if "-" in ion else 1)
    return 0

# Function to format the charge
def format_charge(charge):
    if charge == 0:
        return ""
    sign = "+" if charge > 0 else "-"
    return f"{abs(charge)}{sign}"

# Create the new column "Species"
def create_species(row):
    # Extract charges
    metal_charge = extract_ion_number(row["signed_metal_ion"]) * row["n_metal"]
    ligand_charge = extract_ion_number(row["ligand"]) * row["n_complex"]
    total_charge = metal_charge + ligand_charge

    # Format total charge
    total_charge_str = format_charge(int(total_charge))

    # Format Species column
    metal_ion = row['signed_metal_ion'].split('[')[0]
    ligand = row['ligand'].split('[')[0]
    n_metal = str(int(row['n_metal'])).replace("1","")
    n_ligand = str(int(row['n_complex'])).replace("1","")
    
    if total_charge == 0:
        total_charge_super_script = ""
    else:
        total_charge_super_script = "^"
    
    species = f"[{metal_ion}{n_metal}({ligand}){n_ligand}]{total_charge_super_script}{total_charge_str}"
    return species.replace("_1","").replace("^1","").replace("+1","+").replace("-1","-")

new_df["Species"] = new_df.apply(create_species, axis=1)
new_df["Metal ion"] = new_df["signed_metal_ion"].str.replace("[", "^").str.replace("]","")

new_df

,ligand,metal_ion,n_metal,n_complex,signed_metal_ion,del_G_eV,reference,Species,Metal ion
0,NH3,Ag+,1,1,Ag[1+],0.321990,Bjerrum1957StabilitySubstances,[Ag(NH3)]+,Ag^1+
1,NH3,Ag+,1,2,Ag[1+],-0.190677,Bjerrum1957StabilitySubstances,[Ag(NH3)2]+,Ag^1+
2,NH3,Au+,1,2,Au[1+],-0.325391,Bjerrum1957StabilitySubstances,[Au(NH3)2]+,Au^1+
3,NH3,Au3+,1,4,Au[3+],1.681275,Bjerrum1957StabilitySubstances,[Au(NH3)4]^3+,Au^3+
4,NH3,Ca2+,1,1,Ca[2+],-6.001205,Bjerrum1957StabilitySubstances,[Ca(NH3)]^2+,Ca^2+
...,...,...,...,...,...,...,...,...,...
141,CN[1-],Zn2+,1,4,Zn[2+],4.633763,Smith1989CriticalConstants,[Zn(CN)4]^2-,Zn^2+
142,CN[1-],Pt2+,1,4,Pt[2+],5.646346,Bard2017StandardSolution,[Pt(CN)4]^2-,Pt^2+
144,NO2[1-],Cu2+,1,1,Cu[2+],0.274026,Smith1989CriticalConstants,[Cu(NO2)]+,Cu^2+
145,NO2[1-],Cu2+,1,2,Cu[2+],-0.072720,Smith1989CriticalConstants,[Cu(NO2)2],Cu^2+
146,NO2[1-],Cu2+,1,3,Cu[2+],-0.360299,Smith1989CriticalConstants,[Cu(NO2)3]-,Cu^2+

In [3]:
def generate_ligand_complex_latex_table(df, ligand):
    # Filter the DataFrame for the specific ligand
    combined_data = []
    ligand_data = df[df['ligand'] == ligand]
    for _, row in ligand_data.iterrows():
        combined_data.append({
            'Species': row['Species'],
            'Metal ion': row['Metal ion'],
            'del_G_eV': row['del_G_eV'],
            'Reference': row['reference']
        })

    # Generate the LaTeX table with captions for continued pages
    if ligand == 'Gly[1-]':
        ligand_text = 'Gly-'
    if ligand == 'CN[1-]':
        ligand_text = 'CN-'
    if ligand == 'NH3':
        ligand_text = 'NH3'
    latex_table = fr"""\clearpage
\begin{{longtable}}{{|p{{4cm}}|p{{4cm}}|p{{3cm}}|p{{3cm}}|}}
\caption{{Formation energies of species for \ce{{{ligand_text}}} complexes.}} 
\label{{tab:{ligand}_complex_energies}}
\\
\hline
\textbf{{Species}} & \textbf{{Metal ion}} & \textbf{{\( \Delta G^\circ_{{298}} \) (eV)}} & \textbf{{Reference}} \\ \hline
\endfirsthead
\caption*{{Table \thetable\ continued from previous pages.}} \\
\hline
\textbf{{Species}} & \textbf{{Metal ion}} & \textbf{{\( \Delta G^\circ_{{298}} \) (eV)}} & \textbf{{Reference}} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
"""
    # Add rows to the table
    for i, entry in enumerate(combined_data):
        latex_table += f"\ce{{{entry['Species']}}} & \ce{{{entry['Metal ion']}}} & {entry['del_G_eV']:.3f} & \\textnormal{{\\citenum{{{entry['Reference']}}}}}"
        if i < len(combined_data) - 1:
            latex_table += " \\\\ \\hline\n"
#     for entry in combined_data:
#         latex_table += f"\ce{{{entry['Species']}}} & \ce{{{entry['Metal ion']}}} & {entry['del_G_eV']:.3f} & \\citenum{{{entry['Reference']}}} \\\\ \\hline\n"

    latex_table += r"\end{longtable}"

    # Save the LaTeX table to a file
    output_path = f'data/paper/ligand/{ligand}_complex_energy_table.tex'
    with open(output_path, 'w') as tex_file:
        tex_file.write(latex_table)
#     print(latex_table)
    print(f"LaTeX table saved to {output_path}")

# Example usage
generate_ligand_complex_latex_table(new_df, 'NH3')

generate_ligand_complex_latex_table(new_df, 'Gly[1-]')
generate_ligand_complex_latex_table(new_df, 'CN[1-]')
#

LaTeX table saved to data/paper/ligand/NH3_complex_energy_table.tex
LaTeX table saved to data/paper/ligand/Gly[1-]_complex_energy_table.tex
LaTeX table saved to data/paper/ligand/CN[1-]_complex_energy_table.tex

In [4]:
import json 

def format_species(species):
#     print(species)
    species_text = species.split('(aq)')[0]
    total_charge = extract_ion_number(species_text)
    total_charge_str = format_charge(total_charge)
    if total_charge == 0:
        total_charge_super_script = ""
    else:
        total_charge_super_script = "^"
    species_text = f"{species_text.split('[')[0]}{total_charge_super_script}{total_charge_str}"
    return species_text.replace("_1","").replace("^1","").replace("+1","+").replace("-1","-")

def generate_bulk_metal_latex_table(metal):
    with open(f'data/{metal}_ion_formation_energy.json', 'r') as ion_file:
        ion_data = json.load(ion_file)
    with open(f'data/{metal}_solid_formation_energy.json', 'r') as solid_file:
        solid_data = json.load(solid_file)
        
    combined_data = []
    for species, energy in ion_data.items():
        species_name = format_species(species)
        combined_data.append({'Species': species_name, 'State': 'Aqueous ion', 'Energy': energy})
    for species, energy in solid_data.items():
        species_name = format_species(species)
        combined_data.append({'Species': species_name, 'State': 'Solid', 'Energy': energy})
    latex_table = fr"""\clearpage
\begin{{longtable}}{{|p{{4cm}}|p{{3cm}}|p{{3cm}}|}}
\caption{{Formation energies of {metal} species queried from Materials Project\cite{{Jain2013TheInnovation}}.}} 
\label{{tab:bulk_{metal}_energies}}
\\
\hline
\textbf{{Species}}  & \textbf{{State}} & \textbf{{\( \Delta G\) (eV)}} \\ \hline
\endfirsthead
\caption*{{Table \thetable\ continued from previous pages.}} \\
\hline
\textbf{{Species}}  & \textbf{{State}} & \textbf{{\( \Delta G\) (eV)}} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
"""
    
    for i, entry in enumerate(combined_data):
        latex_table += f"\ce{{{entry['Species']}}} & {entry['State']} & {entry['Energy']:.3f}"
        if i < len(combined_data) - 1:
            latex_table += " \\\\ \\hline\n"
    latex_table += r"\end{longtable}"
    output_path = f'data/paper/metal/{metal}_energy_table.tex'
    with open(output_path, 'w') as tex_file:
        tex_file.write(latex_table)
    print(latex_table)
    print(f"LaTeX table saved to {output_path}")
    
generate_bulk_metal_latex_table('Fe')

\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Fe species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Fe_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{FeO2^2-} & Aqueous ion & -3.011 \\ \hline
\ce{FeOH+} & Aqueous ion & -2.824 \\ \hline
\ce{Fe(OH)3} & Aqueous ion & -6.784 \\ \hline
\ce{FeOH^2+} & Aqueous ion & -4.743 \\ \hline
\ce{FeO4^2-} & Aqueous ion & -3.290 \\ \hline
\ce{Fe^2+} & Aqueous ion & -0.768 \\ \hline
\ce{Fe^3+} & Aqueous ion & 0.002 \\ \hline
\ce{Fe(OH)2+} & Aqueous ion & -4.490 \\ \hline
\ce{FeO2-} & Aqueous ion & -3.767 \\ \hline
\ce{FeHO2-} & Aqueous ion & -3.866 \\ \hline
\ce{Fe100} & Solid & 27.946 \\ \hline
\ce{Fe28} & Solid & 4.908 \\ \hline
\ce{Fe} & Solid & 0.000 \\ \hline
\ce{Fe4} & Solid & 0.068 \\ \hline
\ce{Fe2} & Solid & 0.196 \\ \hline
\ce{Fe6H2} & Solid & 5.815 \\ \hline
\ce{Fe3H} & Solid & 2.917 \\ \hline
\ce{FeH3} & Solid & 2.517 \\ \hline
\ce{Fe2H8} & Solid & 8.721 \\ \hline
\ce{FeH} & Solid & 0.506 \\ \hline
\ce{Fe2H6} & Solid & 6.189 \\ \hline
\ce{Fe4H8O8} & Solid & -6.965 \\ \hline
\ce{Fe16H16O32} & Solid & -71.989 \\ \hline
\ce{FeH2O2} & Solid & -1.673 \\ \hline
\ce{Fe4H4O8} & Solid & -19.690 \\ \hline
\ce{Fe16H20O34} & Solid & -44.238 \\ \hline
\ce{Fe2H2O4} & Solid & -9.439 \\ \hline
\ce{Fe4H14O13} & Solid & -6.242 \\ \hline
\ce{Fe42H2O64} & Solid & -145.257 \\ \hline
\ce{Fe10H2O16} & Solid & -37.318 \\ \hline
\ce{Fe21HO32} & Solid & -70.594 \\ \hline
\ce{Fe14O15} & Solid & -37.651 \\ \hline
\ce{Fe15O16} & Solid & -39.621 \\ \hline
\ce{Fe13O14} & Solid & -34.772 \\ \hline
\ce{Fe4O4} & Solid & -10.585 \\ \hline
\ce{Fe11O12} & Solid & -30.279 \\ \hline
\ce{Fe5O7} & Solid & -15.783 \\ \hline
\ce{Fe13O19} & Solid & -38.495 \\ \hline
\ce{FeO} & Solid & -0.541 \\ \hline
\ce{Fe12O12} & Solid & -29.265 \\ \hline
\ce{Fe32O48} & Solid & -99.453 \\ \hline
\ce{Fe2O6} & Solid & -2.312 \\ \hline
\ce{Fe40O40} & Solid & -83.627 \\ \hline
\ce{Fe12O13} & Solid & -31.988 \\ \hline
\ce{Fe38O39} & Solid & -97.393 \\ \hline
\ce{Fe23O25} & Solid & -63.074 \\ \hline
\ce{Fe2O2} & Solid & -5.255 \\ \hline
\ce{Fe35O36} & Solid & -39.295 \\ \hline
\ce{Fe10O14} & Solid & -30.547 \\ \hline
\ce{Fe21O27} & Solid & -58.877 \\ \hline
\ce{Fe16O18} & Solid & -45.275 \\ \hline
\ce{Fe21O32} & Solid & -69.168 \\ \hline
\ce{Fe8O9} & Solid & -22.422 \\ \hline
\ce{Fe9O10} & Solid & -25.373 \\ \hline
\ce{Fe64O96} & Solid & -223.631 \\ \hline
\ce{Fe16O24} & Solid & -57.830 \\ \hline
\ce{Fe5O8} & Solid & -16.442 \\ \hline
\ce{Fe23O32} & Solid & -75.610 \\ \hline
\ce{Fe4O6} & Solid & -15.171 \\ \hline
\ce{Fe7O8} & Solid & -19.348 \\ \hline
\ce{Fe21O23} & Solid & -57.856 \\ \hline
\ce{Fe32O35} & Solid & -87.753 \\ \hline
\ce{Fe8O12} & Solid & -28.623 \\ \hline
\ce{Fe41O56} & Solid & -134.661 \\ \hline
\ce{Fe2O3} & Solid & -3.287 \\ \hline
\ce{Fe24O32} & Solid & -79.283 \\ \hline
\ce{Fe12O16} & Solid & -40.319 \\ \hline
\ce{Fe12O18} & Solid & -30.420 \\ \hline
\ce{Fe6O8} & Solid & -20.499 \\ \hline
\ce{Fe3O4} & Solid & -9.380 \\ \hline
\ce{Fe9O13} & Solid & -27.197 \\ \hline
\ce{Fe20O32} & Solid & -66.720 \\ \hline
\ce{Fe6O2} & Solid & 6.795 \\ \hline
\ce{Fe2O4} & Solid & -6.397 \\ \hline
\ce{Fe4O8} & Solid & -12.379 \\ \hline
\ce{Fe17O18} & Solid & -45.891 \\ \hline
\ce{Fe20O22} & Solid & -55.652 \\ \hline
\ce{Fe10O11} & Solid & -27.581 \\ \hline
\ce{Fe12O24} & Solid & -33.858 \\ \hline
\ce{Fe43O64} & Solid & -149.513 \\ \hline
\ce{Fe16O34} & Solid & -44.989 \\ \hline
\ce{Fe14O16} & Solid & -39.748 \\ \hline
\ce{Fe13O15} & Solid & -36.844 \\ \hline
\ce{Fe4O13} & Solid & -3.095 \\ \hline
\ce{Fe8O16} & Solid & -24.749 \\ \hline
\ce{FeO2} & Solid & -2.864 \\ \hline
\ce{Fe8O20} & Solid & -17.319 \\ \hline
\ce{Fe8O10} & Solid & -24.179 \\ \hline
\ce{Fe25O32} & Solid & -71.771 \\ \hline
\ce{Fe16O32} & Solid & -42.120\end{longtable}
LaTeX table saved to data/paper/metal/Fe_energy_table.tex

In [5]:
metal_list = ['Ti', 'Cu','Au','Pd','Pt']
for m in metal_list:
    
    generate_bulk_metal_latex_table(m)

\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Ti species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Ti_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{Ti^3+} & Aqueous ion & -4.254 \\ \hline
\ce{TiO2^2+} & Aqueous ion & -5.461 \\ \hline
\ce{TiHO3-} & Aqueous ion & -10.483 \\ \hline
\ce{Ti^2+} & Aqueous ion & -3.889 \\ \hline
\ce{TiO^2+} & Aqueous ion & -6.593 \\ \hline
\ce{Ti100} & Solid & 13.833 \\ \hline
\ce{Ti6} & Solid & 1.862 \\ \hline
\ce{Ti3} & Solid & 0.000 \\ \hline
\ce{Ti} & Solid & 0.062 \\ \hline
\ce{Ti2} & Solid & 0.009 \\ \hline
\ce{TiH2} & Solid & -0.523 \\ \hline
\ce{Ti4H5} & Solid & -1.211 \\ \hline
\ce{TiH} & Solid & -0.172 \\ \hline
\ce{Ti2H4} & Solid & -0.524 \\ \hline
\ce{Ti4H3} & Solid & -0.497 \\ \hline
\ce{Ti4H2} & Solid & -0.252 \\ \hline
\ce{Ti2H2} & Solid & -0.516 \\ \hline
\ce{Ti4H7} & Solid & -1.802 \\ \hline
\ce{Ti4H6} & Solid & -1.477 \\ \hline
\ce{Ti6H4O14} & Solid & -56.548 \\ \hline
\ce{Ti6H4O8} & Solid & -26.848 \\ \hline
\ce{Ti11H7O24} & Solid & -97.316 \\ \hline
\ce{Ti6H2O13} & Solid & -57.681 \\ \hline
\ce{Ti2H2O3} & Solid & -8.815 \\ \hline
\ce{Ti6H8O16} & Solid & -44.243 \\ \hline
\ce{Ti2H4O4} & Solid & -5.950 \\ \hline
\ce{Ti4O8} & Solid & -39.486 \\ \hline
\ce{TiO2} & Solid & -9.416 \\ \hline
\ce{Ti8O16} & Solid & -78.487 \\ \hline
\ce{Ti2O4} & Solid & -19.705 \\ \hline
\ce{Ti16O32} & Solid & -154.710 \\ \hline
\ce{Ti12O24} & Solid & -117.043 \\ \hline
\ce{Ti20O22} & Solid & -112.989 \\ \hline
\ce{Ti3O6} & Solid & -29.172 \\ \hline
\ce{Ti6O14} & Solid & -53.840 \\ \hline
\ce{Ti26O44} & Solid & -222.663 \\ \hline
\ce{Ti10O18} & Solid & -90.208 \\ \hline
\ce{Ti16O30} & Solid & -148.980 \\ \hline
\ce{Ti4O5} & Solid & -26.236 \\ \hline
\ce{Ti11O14} & Solid & -73.022 \\ \hline
\ce{Ti4O14} & Solid & -28.681 \\ \hline
\ce{Ti6O6} & Solid & -30.810 \\ \hline
\ce{Ti3O3} & Solid & -16.498 \\ \hline
\ce{Ti8O14} & Solid & -70.553 \\ \hline
\ce{Ti50O50} & Solid & -244.764 \\ \hline
\ce{Ti11O18} & Solid & -91.424 \\ \hline
\ce{Ti5O5} & Solid & -27.069 \\ \hline
\ce{TiO} & Solid & -5.304 \\ \hline
\ce{Ti2O2} & Solid & -10.469 \\ \hline
\ce{Ti39O65} & Solid & -310.876 \\ \hline
\ce{Ti4O6} & Solid & -31.134 \\ \hline
\ce{Ti75O25} & Solid & -120.814 \\ \hline
\ce{Ti18O36} & Solid & -175.126 \\ \hline
\ce{Ti30O60} & Solid & -281.726 \\ \hline
\ce{Ti9O10} & Solid & -50.331 \\ \hline
\ce{Ti3O4} & Solid & -20.880 \\ \hline
\ce{Ti68O34} & Solid & -164.226 \\ \hline
\ce{Ti4O3} & Solid & -16.095 \\ \hline
\ce{Ti10O14} & Solid & -69.546 \\ \hline
\ce{Ti21O21} & Solid & -107.247 \\ \hline
\ce{Ti16O28} & Solid & -137.327 \\ \hline
\ce{Ti15O24} & Solid & -122.609 \\ \hline
\ce{Ti6O2} & Solid & -11.062 \\ \hline
\ce{Ti7O8} & Solid & -41.326 \\ \hline
\ce{Ti6O} & Solid & -6.018 \\ \hline
\ce{Ti14O26} & Solid & -129.408 \\ \hline
\ce{Ti18O16} & Solid & -83.045 \\ \hline
\ce{Ti12O22} & Solid & -109.934 \\ \hline
\ce{Ti8O13} & Solid & -66.305 \\ \hline
\ce{Ti18O34} & Solid & -168.555 \\ \hline
\ce{Ti19O30} & Solid & -153.701 \\ \hline
\ce{Ti6O3} & Solid & -16.922 \\ \hline
\ce{Ti2O} & Solid & -5.790 \\ \hline
\ce{Ti12O2} & Solid & -12.200 \\ \hline
\ce{Ti10O13} & Solid & -68.048 \\ \hline
\ce{Ti6O4} & Solid & -22.259 \\ \hline
\ce{Ti12O18} & Solid & -91.300 \\ \hline
\ce{Ti8O12} & Solid & -61.779 \\ \hline
\ce{Ti12O4} & Solid & -23.852 \\ \hline
\ce{Ti6O10} & Solid & -50.912 \\ \hline
\ce{Ti18O6} & Solid & -35.649 \\ \hline
\ce{Ti9O13} & Solid & -64.672 \\ \hline
\ce{Ti3O8} & Solid & -24.885\end{longtable}
LaTeX table saved to data/paper/metal/Ti_energy_table.tex
\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Cu species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Cu_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{CuO} & Aqueous ion & -1.080 \\ \hline
\ce{CuOH+} & Aqueous ion & -1.487 \\ \hline
\ce{Cu^2+} & Aqueous ion & 0.501 \\ \hline
\ce{CuO2^2-} & Aqueous ion & -2.082 \\ \hline
\ce{CuHO2-} & Aqueous ion & -2.858 \\ \hline
\ce{Cu+} & Aqueous ion & 0.339 \\ \hline
\ce{Cu2H2} & Solid & 1.480 \\ \hline
\ce{Cu4} & Solid & 0.023 \\ \hline
\ce{Cu2} & Solid & 0.015 \\ \hline
\ce{Cu} & Solid & 0.000 \\ \hline
\ce{Cu6} & Solid & 0.955 \\ \hline
\ce{CuHO2} & Solid & -2.655 \\ \hline
\ce{Cu2H4O4} & Solid & -0.353 \\ \hline
\ce{Cu2H2O4} & Solid & -5.381 \\ \hline
\ce{Cu9O13} & Solid & -10.547 \\ \hline
\ce{Cu2O2} & Solid & -3.138 \\ \hline
\ce{Cu8O7} & Solid & -10.256 \\ \hline
\ce{Cu4O2} & Solid & -3.234 \\ \hline
\ce{Cu8O} & Solid & -0.558 \\ \hline
\ce{Cu2O4} & Solid & -1.723 \\ \hline
\ce{Cu8O6} & Solid & -9.404 \\ \hline
\ce{Cu3O3} & Solid & -3.041 \\ \hline
\ce{Cu6O8} & Solid & -9.177 \\ \hline
\ce{Cu8O12} & Solid & -11.940 \\ \hline
\ce{Cu64O} & Solid & 0.470 \\ \hline
\ce{CuO2} & Solid & -0.956 \\ \hline
\ce{Cu3O2} & Solid & -2.384 \\ \hline
\ce{Cu6O} & Solid & 8.620 \\ \hline
\ce{Cu16O16} & Solid & -19.357 \\ \hline
\ce{Cu4O8} & Solid & -3.699 \\ \hline
\ce{Cu4O6} & Solid & -6.380 \\ \hline
\ce{Cu10O14} & Solid & -11.877 \\ \hline
\ce{Cu16O24} & Solid & -25.724 \\ \hline
\ce{Cu4O4} & Solid & -1.560 \\ \hline
\ce{CuO} & Solid & -1.227 \\ \hline
\ce{Cu8O8} & Solid & -10.106\end{longtable}
LaTeX table saved to data/paper/metal/Cu_energy_table.tex
\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Au species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Au_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{H2AuO3-} & Aqueous ion & -3.336 \\ \hline
\ce{Au^3+} & Aqueous ion & 3.382 \\ \hline
\ce{AuO3^3-} & Aqueous ion & -1.610 \\ \hline
\ce{HAuO3^2-} & Aqueous ion & -2.547 \\ \hline
\ce{H3AuO3} & Aqueous ion & -4.010 \\ \hline
\ce{Au} & Solid & 0.000 \\ \hline
\ce{Au2} & Solid & 0.011 \\ \hline
\ce{HAuO2} & Solid & -1.666 \\ \hline
\ce{H2Au2O4} & Solid & -3.490 \\ \hline
\ce{Au4O6} & Solid & -2.678 \\ \hline
\ce{Au6O2} & Solid & 2.206\end{longtable}
LaTeX table saved to data/paper/metal/Au_energy_table.tex
\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Pd species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Pd_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{Pd^2+} & Aqueous ion & 1.452 \\ \hline
\ce{Pd} & Solid & 0.000 \\ \hline
\ce{Pd4} & Solid & 0.027 \\ \hline
\ce{Pd2} & Solid & 0.045 \\ \hline
\ce{Pd42O48} & Solid & -50.494 \\ \hline
\ce{PdO} & Solid & -0.364 \\ \hline
\ce{Pd7O8} & Solid & -8.282 \\ \hline
\ce{Pd2O2} & Solid & -2.526 \\ \hline
\ce{Pd4O2} & Solid & -1.694 \\ \hline
\ce{Pd2O4} & Solid & -3.098 \\ \hline
\ce{PdO2} & Solid & -0.858 \\ \hline
\ce{H3Pd4} & Solid & 1.449 \\ \hline
\ce{H4Pd3} & Solid & 2.946 \\ \hline
\ce{HPd} & Solid & 0.517 \\ \hline
\ce{HPd3} & Solid & 2.566 \\ \hline
\ce{H2Pd2} & Solid & 0.954 \\ \hline
\ce{H2Pd6} & Solid & 5.182\end{longtable}
LaTeX table saved to data/paper/metal/Pd_energy_table.tex
\clearpage
\begin{longtable}{|p{4cm}|p{3cm}|p{3cm}|}
\caption{Formation energies of Pt species queried from Materials Project\cite{Jain2013TheInnovation}.}
\label{tab:bulk_Pt_energies}
\\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endfirsthead
\caption*{Table \thetable\ continued from previous pages.} \\
\hline
\textbf{Species}  & \textbf{State} & \textbf{\( \Delta G\) (eV)} \\ \hline
\endhead
\hline
\endfoot
\hline
\endlastfoot
\ce{Pt^2+} & Aqueous ion & 1.925 \\ \hline
\ce{Pt} & Solid & 0.000 \\ \hline
\ce{Pt2} & Solid & 0.138 \\ \hline
\ce{H2Pt6} & Solid & 5.437 \\ \hline
\ce{H12Pt3} & Solid & 12.820 \\ \hline
\ce{H6Pt2} & Solid & 7.873 \\ \hline
\ce{HPt3} & Solid & 2.734 \\ \hline
\ce{Pt2O4} & Solid & -4.293 \\ \hline
\ce{PtO} & Solid & 0.729 \\ \hline
\ce{PtO2} & Solid & -2.132 \\ \hline
\ce{Pt4O8} & Solid & -7.564 \\ \hline
\ce{Pt2O12} & Solid & 1.841 \\ \hline
\ce{Pt6O8} & Solid & -9.041 \\ \hline
\ce{Pt2O2} & Solid & -1.704 \\ \hline
\ce{Pt2O6} & Solid & -2.965 \\ \hline
\ce{Pt4O2} & Solid & 0.353 \\ \hline
\ce{Pt4O12} & Solid & -5.717 \\ \hline
\ce{Pt3O4} & Solid & 2.948 \\ \hline
\ce{H16Pt2O12} & Solid & 4.378\end{longtable}
LaTeX table saved to data/paper/metal/Pt_energy_table.tex